github: [metadata]

remote_theme: dieghernan/chulapa
#theme: chulapa-jekyll

repository: bartoinfo/bartoinfo.github.io
url: "https://bartoinfo.github.io"
baseurl: "/"

title: Barto Info
subtitle: Site da Primeira Edição do Dia da Informática da ETEC Barto
description: Realização da Primeira Edição do Dia da Informática da ETEC Barto, com o objetivo de promover a cultura digital e a inclusão tecnológica.
lang: pt-BR
og_image: "./assets/img/site/banner.png"
#twitter_site: dhernangomez
timezone: "America/Sao_Paulo"
author:
  name: clcmo
  avatar: ./assets/img/site/clcmo-avatar.png
  location: São Paulo, Brazil
  links:
    - url: https://github.com/clcmo/
      icon: "fab fa-github"
      label: GitHub
    - url: https://clcmo.github.io/
      icon: fas fa-blog
      label: Blog
    - url: https://stackoverflow.com/users/7433503/camila-l-oliveira
      icon: "fab fa-stack-overflow"
      label: StackOverflow

gtag_id:  UA-139034853-5

search:
  provider: algolia
  algolia_logo: true

algolia:
  application_id        : "KOIKA5PDQO"
  index_name            : "bartoinfo"
  search_only_api_key   : "7f1fe42bef3f03458cb3a911ebc7e0ac"
  files_to_exclude:         #Optional
    - _layouts/*.html
    - _includes/*.html
    - _pages/liquid*
  extensions_to_index:      #Optional
    - html
    - md
  searchableAttributes:     #Optional
    - title
    - headings
    - unordered(content)
    - unordered(subtitle)
    - unordered(categories)
    - unordered(collection)
    - unordered(tags)
  customRanking:            #Optional
    - desc(include_on_search)
    - desc(title)
    - desc(content)
    - desc(subtitle)
comments:
  provider: giscus
  cusdis_app_id: "ba6333c9-c7b1-4578-a932-e9ee3e71f120"
  website_id: "XaFqz82GQETRJnLi7verVsyBS" 

google_cse_id: 002514516175957445995:tvgnhtemtbu

# B. Navigation
navbar:
  style :  fab
  brand:
    title :  Home
    img: "./assets/img/site/brand-white.png"
  nav:
  - title: Blog
    url: /blog/
  - title: Sobre
    child:
     - title: O que é o BartoInfo?
       url: /sobre/o-que-e-barto-info
     - title: O que é a ETEC Barto?
       url: /sobre/quem-e-etec-barto
     - title: O dia da informática
       url: /sobre/dia-da-informatica
  - title: Sobre o Site
    child:
      - title: Licença
        url: /docs/licenca
      - title: Contribua
        url: /docs/contribua
      - title: Changelog
        url: https://github.com/bartoinfo/bartoinfo.github.io/blob/master/CHANGELOG.md
  - title: Contato
    url: /contato

footer:
  links:
    - label: "RSS"
      icon: "fa fa-rss"
      url:  "./atom.xml"
    - label: "GitHub"
      icon: "fab fa-github"
      url: https://github.com/bartoinfo/
    - label: "My blog"
      icon: "fas fa-blog"
      url: "https://bartoinfo.github.io/"
  copyright: "&copy; 2025 <span class='chulapa'>BartoInfo</span> e o time ETEC Barto. Todos os direitos reservados."

# C. Theme Settings
chulapa-skin:
  highlight   : "vs"
  skin        : navi
  autothemer  :  true

# D. Jekyll Defaults and collections: see https://jekyllrb.com/
collections:
  sobre:
    output: true
    permalink: /sobre/:name
  docs:
    output: true
    permalink: /docs/:name
  posts:
    output: true
    permalink : /blog/:day/:month/:year/:title
collections_dir     : collections
permalink           : /:day/:month/:year/:title
paginate: 4
paginate_path: /blog/page:num/
paginator_maxnum: 3
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      header_type         : "base"
      include_on_search   : false
      cloudtag_url        : "/tags"
      cloudcategory_url   : "/categories"
      show_seo            : true
  -
    scope:
      path: ""
      type: "docs"
    values:
      header_type       : "hero"
      show_sidetoc      : true
      include_on_search : true
      show_bottomnavs   : true
      show_comments     : true
      show_breadcrumb   : true
      og_image: "/assets/img/site/banner-docs.png"
      breadcrumb_list   :
        - label: Home
          url: /
        - label: Docs
          url: /docs
  -
    scope:
      path: ""
      type: "posts"
    values:
      header_type       : "post"
      include_on_search : true
      include_on_feed   : true
      show_date         : true
      show_related      : true
      show_bottomnavs   : true
      show_sociallinks  : true
      show_comments     : true
      show_tags         : true
      show_categories   : true
      show_author       : true
      show_breadcrumb   : true
      breadcrumb_list   :
        - label: Blog
          url: /blog/
  -
    scope:
      path: ""
      type: "skins"
    values:
      header_type       : "splash"
      cloudtag_url      : "/demo/tags"
      og_image          : '/assets/img/site/banner-skins.png'
      include_on_search : true
      show_date         : true
      show_sociallinks  : true
      show_comments     : true
      show_tags         : true
      show_categories   : true
      show_related      : true 
      related_label     : '<p><i class="fa-solid fa-right-left"></i></p>'
      show_random       : true 
      random_label      : '<p><i class="fa-solid fa-shuffle"></i></p>'
      show_bottomnavs   : true
      show_author       : true
      show_toc          : true
      show_sidetoc      : true
      show_breadcrumb   : true
      show_seo          : false
      breadcrumb_list   :
        - label: Skins
          url: /skins
  -
    scope:
      path: ""
      type: "demo"
    values:
      layout            : "default"
      header_type       : "base"
      cloudtag_url      : "/demo/tags"
      og_image          : '/assets/img/site/banner-demos.png'
      include_on_search : true
      cloudcategory_url : "/demo/category"
      show_breadcrumb   : true
      breadcrumb_list   :
        - label: Demo
          url: /demo
  -
    scope:
      path: "assets/img/gallery"
    values:
      image_col         : gallery

# XX. Other settings - no need to modify
compress_html:
  clippings: all
  blanklines: true
plugins:
  - jekyll-github-metadata
  - jekyll-paginate
  - jekyll-include-cache
  - jekyll-sitemap
  - jekyll-remote-theme
exclude:
  - LICENSE
  - README.md
  - Gemfile
  - vendor
  - www_src
include:
 - _pages
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  footnote_backlink: '&uarr;'
  entity_output: as_char
  toc_levels: 2..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

sass:
  sass_dir: _sass
  style: compressed
  quiet_deps: true
  silence_deprecations:
    - import
    - global-builtin
    - color-functions
    - mixed-decls
    - abs-percent
    - function-units
    - color-functions

