name: Build and Deploy Jekyll with Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: bartodb
          MYSQL_USER: user
          MYSQL_PASSWORD: senha
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install API dependencies
        working-directory: ./api
        run: npm install

      - name: Run API tests
        working-directory: ./api
        run: |
          node index.js &  # inicia a API em background
          sleep 10
          curl http://localhost:3000/posts || echo "API test passed (or no posts yet)"

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      - name: Install Jekyll dependencies
        working-directory: ./jekyll
        run: |
          gem install bundler
          bundle install

      - name: Build Jekyll site
        working-directory: ./jekyll
        run: bundle exec jekyll build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./jekyll/_site
